title: Blog Template
lang: ja
url:
tagline: short description
description: long description
author:
  name:
  url:
twitter:
  username:
  card: summary
logo: /pages-blog-template-minimal/assets/img/logo.jpg
google_site_verification:
google_analytics:
show_downloads: false
github:
  is_project_page: true
  is_user_page: true
theme: jekyll-theme-minimal
plugins:
  - jekyll-sitemap
configs:
  favicon_assets: /pages-blog-template-minimal/assets/favicons/
  is_multi_favicon: true
  is_mathjax: true
  is_pagetop_button: true
  is_homepage_button: true
