title: Blog Template
lang: ja
url:
tagline: short description
description: long description
author:
  name: Yuki Sakishita
  url: https://y-saki26.github.io/
twitter:
  username:
  card: summary
logo: /assets/img/logo.jpg
google_site_verification:
google_analytics:
github:
  is_project_page: true
  is_user_page: true
theme: jekyll-theme-minimal
plugins:
  - jekyll-sitemap
show_downloads: false
configs:
  favicon_assets: /pages-blog-template-minimal/assets/favicons/
  is_multi_favicon: true
  is_mathjax: true
  is_pagetop_button: true
  is_homepage_button: true
