title: Blog Template
description: Blog Template on GitHub Pages with Jekyll theme Miminal
url: https://y-saki26.github.io/pages-blog-template-minimal/
logo: /assets/img/logo.png
favicon_assets: /pages-blog-template-minimal/assets/favicons/
show_downloads: false
github:
  is_project_page: true
  is_user_page: true
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-sitemap
configs:
  is_page_top: true
  is_homepage: false
  is_update_date: true
