title: Blog Template
description: Blog Template on GitHub Pages with Jekyll theme Miminal
logo: /assets/img/logo.png
show_downloads: false
github:
  is_project_page: true
  is_user_page: true
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-sitemap
configs:
  favicon_assets: /pages-blog-template-minimal/assets/favicons/
  is_multi_favicon: true
  is_mathjax: true
  is_page_top: true
  is_update_date: true
