title: Blog Template
url: https://y-saki26.github.io/pages-blog-template-minimal/
logo: /assets/img/logo.png
description: Blog Template on GitHub Pages with Jekyll theme Miminal
show_downloads: false
github:
  is_project_page: true
  is_user_page: true
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-sitemap
